name: building, linting, testing
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    pipeline:
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                node-version: [17.x]
        permissions:
          contents: write
          pull-requests: write
        steps:
            - uses: actions/checkout@v2
            - name: Staring Node.js ${{matrix.node-version}}
              uses: actions/setup-node@v1
              with:
                node-version: ${{matrix.node-version}}
            - name: install modules
              run: npm install
            - name: production building
              run: npm run build:prod
            - name: ts linting
              run: npm run lint:ts
              if: always
            - name: css linting
              run: npm run lint:scss
              if: always
            - name: unit testing
              run: npm run test:unit
              if: always
            - name: sb build
              run: npm run storybook:build
              if: always
            - name: screenshot testing
              run: npm run test:ui:ci
              if: always
            
            
